name: matrix statergy

on: workflow_dispatch

jobs:
  deploy-job:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        images: [Hello-world, alpine]
      
    runs-on: ${{matrix.os}}
    steps:
      - name: Echo text
        run: docker info
      - name: run image on ${{matrix.os}}
        run: docker run ${{matrix.images}}