name: matrix strategy

on: push

jobs:
  deploy-job:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        images: [hello-world, alpine]
      
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker info
        run: docker info
      - name: Run Docker image
        run: docker run ${{ matrix.images }}
